### ISSUE TITLE
Render is in black and white colors

### ISSUE THREAD

**Issue by ranbuch** [taseenb/THREE.Highres#1]
Looks like the Highres render ignores lights

**Comment by ranbuch** [comment]
On the `normal` (+) mode seems to work fine but the `depth` (-) mode always terns out black

**Comment by taseenb** [comment]
Not enough information, can you show some code and an image? A jsfiddle or codepen would help.

**Comment by ranbuch** [comment]
@taseenb on you example [here](https://taseenb.github.io/THREE.Highres/demo/index.html) I thought that the image is all black and white when actually the small shapes on the back of the scene are dark gray.

Please close this issue and forgive me for the false alarm.
